### Задание 2
Создайте модель под названием model с помощью RandomForestRegressor из модуля sklearn.ensemble.
Сделайте агрумент n_estimators равным 1000,
max_depth должен быть равен 12 и random_state сделайте равным 42.
Обучите модель на тренировочных данных аналогично тому, как вы обучали модель LinearRegression,
но при этом в метод fit вместо датафрейма y_train поставьте y_train.values[:, 0],
чтобы получить из датафрейма одномерный массив Numpy,
так как для класса RandomForestRegressor в данном методе для аргумента y предпочтительно применение массивов вместо датафрейма.
Сделайте предсказание на тестовых данных и посчитайте R2. Сравните с результатом из предыдущего задания.
Напишите в комментариях к коду, какая модель в данном случае работает лучше.

In [40]:
import sys; sys.path.insert(0, '..')
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

from lib.Core import (
    TEST_RANGE, RANDOM_SEED, PRICE,
    load_data, train_model
)

In [41]:
RANDOM_FOREST_REGRESSOR = 'RandomForestRegressor'
LINEAR_REGRESSION = 'LinearRegression'

ESTIMATORS = 1000
DEPTH = 12

In [42]:
X, y = load_data()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=TEST_RANGE, random_state=RANDOM_SEED)

In [43]:
# Test with RandomForestRegressor
model = RandomForestRegressor(n_estimators=ESTIMATORS, max_depth=DEPTH, random_state=RANDOM_SEED)

train_results_A, score_A = train_model(
    X_train,
    y_train.values[:, 0],
    X_test,
    y_test[PRICE],
    model=model
)

In [44]:
# Test with LinearRegression
train_results_B, score_B = train_model(
    X_train,
    y_train,
    X_test,
    y_test[PRICE]
)

In [45]:
train_results_A

     Correct   Precited     Error
173     23.6  22.806412 -0.793588
274     32.4  31.131464 -1.268536
491     13.6  16.339125  2.739125
72      22.8  23.810726  1.010726
452     16.1  17.139521  1.039521
..       ...        ...       ...
441     17.1  13.521640 -3.578360
23      14.5  15.112621  0.612621
225     50.0  42.808700 -7.191300
433     14.3  15.586103  1.286103
447     12.6  16.072425  3.472425

[152 rows x 3 columns]

In [46]:
train_results_B

     Correct   Precited      Error
173     23.6  28.648960   5.048960
274     32.4  36.495014   4.095014
491     13.6  15.411193   1.811193
72      22.8  25.403213   2.603213
452     16.1  18.855280   2.755280
..       ...        ...        ...
441     17.1  17.403672   0.303672
23      14.5  13.385941  -1.114059
225     50.0  39.983425 -10.016575
433     14.3  16.682863   2.382863
447     12.6  18.285618   5.685618

[152 rows x 3 columns]

In [47]:
print(f'{RANDOM_FOREST_REGRESSOR} Score : {score_A}')
print(f'{LINEAR_REGRESSION} Score      : {score_B}')
print(f'Better result with          : {RANDOM_FOREST_REGRESSOR if score_A > score_B else LINEAR_REGRESSION}')

RandomForestRegressor Score : 0.8479049999699443
LinearRegression Score      : 0.669370269149561
Better result with          : RandomForestRegressor